# This is a basic workflow to help you get started with Actions

name: StudieGPS adoc to HTML

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'studie_gps.adoc'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Convert .adoc to HTML
        run: |
          asciidoctor studie_gps.adoc
